Iteracio1
codicoop/castellet_app pull request #2
Opened 2024-05-10 14:41 UTC by jvncode

Iteracio1

2024-05-29 14:32 UTC, perepicornell requested changes
Està tot molt bé en general, he fet uns quants pushes de coses que volia tirar milles, i deixo un parell de comentaris de coses a canviar.

2024-05-29 14:32 UTC, perepicornell commented on src/apps/users/migrations/0003_data_emails.py
>          per a {{absolute.url}}.</p>
Això no funciona, si generes el mail veuràs que la string queda en blanc.

2024-05-29 14:32 UTC, perepicornell commented on src/apps/users/migrations/0003_data_emails.py
>          per a {{absolute.url}}.</p>
Important en el futur revisar bé els emails que es generen per veure que tots els valors surten bé, això tb es podria fer a nivell de unit test, ja que és força pesat fer les validacions a ma...

2024-05-29 14:32 UTC, perepicornell commented on src/apps/main/models.py
>  class Newsletter(models.Model):
He anat veient un error a diversos llocs (traduccions, panell admin etc.) sobre el tema del butlletí.

Em trobava frases com "S'ha creat un nou butlletí" (p.ex. quan una persona es subscriu a la newsletter), lo qual no tenia cap sentit pq no s'ha creat cap butlletí, el que s'ha creat és una subscripció al butlletí.

Ara m'adono que l'arrel del problema és el nom d'aquest model.

No s'hauria de dir Newsletter sinó "persona subscrita al butlletí", és a dir: `NewsletterSubscriber`

Please @jvncode fes un refactor per canviar el nom del model (aprofitant que ara no està a producció i podem fer un canvi així :P)

Recorda de modificar també el `Meta` del model.

2024-05-30 15:25 UTC, jvncode commented on src/apps/users/migrations/0003_data_emails.py
>          per a {{absolute.url}}.</p>
Resolt!
Perdó, error meu, imagino que ho vaig revisar però se'm va passar aquest valor.

2024-05-30 16:28 UTC, jvncode commented on src/apps/main/models.py
>  class Newsletter(models.Model):
Efectivament, té més lògica que es denomini "NewsletterSubscriber".
He modificat el model, els forms, views i tests, ara tot és NewsletterSubscriber.
Li he donat un repàs a l'app i he actualitzat tests.

2024-05-31 07:57 UTC, merged